export const ACTIVE_SIDEBAR_BRAND = "ACTIVE_SIDEBAR_BRAND";
export const EMPLOYEE_LIST = "EMPLOYEE_LIST";
export const ADD_NEW_EMPLOYEE = "ADD_EMPLOYEE";
export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const EDIT_EMPLOYEE = "EDIT_EMPLOYEE";





